### ISSUE TITLE
[Crash] Client & Server

### ISSUE THREAD

**Issue by QAngelusQ** [TheIllusiveC4/ConstructsArmory#1]
https://pastebin.com/QxPxzDd3 - Client
https://pastebin.com/KKem8H5w - Server

Im pretty sure its the same error message

**Comment by TheIllusiveC4** [comment]
The reason is because something registered a modifier/trait with the same name as one that I have coded in (although it's currently unused) - "sticky". This would have to be from another mod besides Tinkers' Construct since my internal dev build doesn't crash. 

I'm going to make a new build with the appropriate modifiers commented out so it doesn't crash like that anymore, but do you know what is adding this "sticky" modifier/trait?

**Comment by QAngelusQ** [comment]
The Yoyo's Mod adds the Sticky Trait 

Here's the link to the [Source](https://github.com/Jozufozu/Yoyos/blob/10cdc0f99a72b9cf87afa24905d6184aac5535a0/src/main/java/com/jozufozu/yoyos/tinkers/traits/TraitSticky.java)

Also here's a [link](https://minecraft.curseforge.com/projects/yoyos) to the mod

Thanks!
