### ISSUE TITLE
Enhancement request: Ability to replace accessory

### ISSUE THREAD

**Issue by dralom** [TheIllusiveC4/ConstructsArmory#104]
I don't know if not being able to replace an accessory is intended behavior, but if it is I wish I knew before I applied the Traveler's Knapsack to my chestplate. Now that I can finally make an invisibility cloak I am disappointed to find that I cannot replace the knapsack with the cloak without building a whole new chestplate (which means losing all the materials and effort put into building and upgrading the current chestplate).

**Comment by TheIllusiveC4** [comment]
It's intended behavior. I can understand your desire to have known this before constructing your armor, but I'm not sure how to make this more obvious to players since I don't see any reason to believe that they would be replaceable in the first place. They are, essentially, just modifiers and modifiers cannot be replaced.
