### ISSUE TITLE
Tough as Nails Please reconsider stance on proper integration.

### ISSUE THREAD

**Issue by Guinaro** [TheIllusiveC4/ConstructsArmory#105]
Please reconsider your stance on Tough as Nails Armor integration.
Currently in my modpack with Constructs Armory, Tough as Nails, Serene Seasons and B3M Time speed mod. I am unable to play the game during winter time (lasts about 180 hours, with 2 hour days) (summer too).
TANs armor pieces are woefully inadequate to allow you to play. I tried Tinker's Survival, and though it provides you with armor pieces/parts that can help you if configured properly, that mod introduces a whole other level of pain, by having many parts of that mod that you cannot disable: e.g. child laughter, only harvesting with tools, ...

So I kindly request you for crafttweaker configurable armor material, pieces, modifiers, ...
Different ways are possible to solve the issue.
1. Having different materials like wool, chilled slime, ... to add to your gear that provide different levels of heating or cooling. At least make it that each seperate part core, trim, plates, ... have a combined influence instead of like Tinker Survival having 1 or 3 parts provide the same level of healing or cooling.
2. Have different modifiers that each can add a level of heating or cooling.
It would be nice if we could build up to e.g. 3 levels like Modifier 1: Wool, Modifier 2: Magma Shard, Modifier 3: Heating Coil. If possible each needing the previous level present aswell.

3. You could also have Materials have heating and cooling stats/traits, which you could expose with crafttweaker functionality. This way as modpack creators we could each give a material it's own heating or cooling stat. (This last one has my preference, because it once again makes creating the perfect armor that more of a challenge or better you need different armor sets to properly enjoy/survive the game.)
I strongly recommend to set temperature modifiers to 0 for standard gameplay and force modpack creators to configure via crafttweaker functionality their own requirements.

In config it would be preferable to be able to set wether material parts combine their stats or not. For those that want to let the biggest modifier dominate. Combining could result in combo's that heat and cool and resulting in effectively 0 temperature change.
Also being able to set to use modifiers and if so, how much heating/cooling each (different) modifier adds.
If we could configure which item for which modifier is required that would even be better, so that we can use modded items too.

All of those need to be highly modifiable as TAN allows us to set temperature levels ourselves too, so we could go for a much greater spread that standard TAN. Allow modpack makers to make a more balanced/challenged survival game.

Guinaro

**Comment by TheIllusiveC4** [comment]
I respect your well-constructed suggestion, however I am still not going to implement any integration. My stance on TaN has less to do with its mechanical considerations and more to do with my stance on any mod support, which you can find in the FAQ:

> Q. Can you add a modifier/material to support (insert mod here)?
A. No. I could, but I won't. As soon as I add support for one mod, then I won't have any reason not to add support for any and all mods. Considering the scope of possibilities, this is a huge endeavor and will only end up bloating this mod with a bunch of optional features. In addition, I'd rather have the other mods add support on their end because then they have full control over what kind of integration to introduce, if any.

Perhaps one day I will construct my own separate add-on for the full suite of integration features that people have been asking for, but that's the only way you'll see this sort of thing from me personally.
