### ISSUE TITLE
Goggles of Revealing attachement

### ISSUE THREAD

**Issue by angelnc1989** [TheIllusiveC4/ConstructsArmory#114]
It would be nice to have a headgear attachement that gives Contruct's Armory armor Goggles of Revealing properties. It's pretty annoying to have to swap around armor pieces all the time.

**Comment by TheIllusiveC4** [comment]
From the FAQ:
> Q. Can you add a modifier/material to support (insert mod here)?
A. No. I could, but I won't. As soon as I add support for one mod, then I won't have any reason not to add support for any and all mods. Considering the scope of possibilities, this is a huge endeavor and will only end up bloating this mod with a bunch of optional features. In addition, I'd rather have the other mods add support on their end because then they have full control over what kind of integration to introduce, if any.
