### ISSUE TITLE
[1.12.2] [Request] Overlapping Backpacks

### ISSUE THREAD

**Issue by Draskh** [TheIllusiveC4/ConstructsArmory#120]
This is not a bug, more a cosmetic things. There is no option to turn off the rendering of the Knappsack, so it overlapps with other backpack mods. 
Same as: https://github.com/DreenDex/ImprovedBackpacks-Issues/issues/7

![2018-10-04_16 04 29](https://user-images.githubusercontent.com/26455012/46483746-a6429b80-c7f8-11e8-869a-cb61c4a1654f.png)

**Comment by TheIllusiveC4** [comment]
There's not much I can do for this, I'm afraid. 

Even if I implemented an option to turn off the rendering for the knapsack, this does nothing to solve the main issue that rendering overlaps will sometimes occur beyond developer control due to the varied nature of mods. This problem could easily be applied to the goggles, the belt, and even the armor itself. Rendering anything makes no guarantees about where it comes from, so mutual exclusion is difficult to achieve.

In addition, turning off the rendering entirely for the knapsack seems like it could lead to clunky behavior if its usage still remains active. If the usage can be activated and deactivated, this presents some additional logistic concerns and adds the overhead of another keybinding.
