### ISSUE TITLE
Suggestion: Can you please add a key to activate/deactivate "glowing" from shoes?

### ISSUE THREAD

**Issue by StefanArmand** [TheIllusiveC4/ConstructsArmory#131]
Hello! I love you mod so far, and this is the only thing that really bothers me and I wanted to mention it.

Sometimes I just want to travel and not automatically place lights in the places I travel to. Same when building new huge structures or when fighting random mobs on the field for weapon xp. I am forced to take the shoes off in these situations. I found glowing very useful when mining only. It would be great to be able to toggle on or off the glowing like we can do with accessories.

**Comment by Thunder-Nova** [comment]
Hmm... Then glowing becomes an accessory.

But with level up, you can easily make a second pair of shoes and level them up by standing on a cactus or similar.

I wear glowing unbreakable boots mainly for mining or exploring. But for battle I get more defensive so I got a second pair.

I am not completely for the idea of command due to making just glowing into an accessory, but if we make an accessory series for boots, such as flippers (for faster swimming), wheels (right click rails, to ride them faster then minecarts), blades (move faster on ice), and Heavy (can't swim, walk normal speed as on surface, underwater, can be disabled) Then glowing accessory can be possible to change to.

**Comment by StefanArmand** [comment]
What you mention does sound great, but I wouldn't want to suggest something so complicated, for me a simple toggle key for the glowing effect would be more than enough. It would make the boots perfect, and we wouldn't need two pairs.

**Comment by Thunder-Nova** [comment]
Well what I am trying to input is more in terms of what @TheIllusiveC4 said about toggleble options, it has to become an accessory. Which includes things that add more to cosmetic such as flippers for boots.

The thing is last time I checked there aren't any accessory for boots. So better to make a list.

**Comment by TheIllusiveC4** [comment]
Sorry, but I won't be adding toggleability.

When you say 
> we wouldn't need two pairs

, this is the exact opposite of what I want. I want players to have multiple sets of armor for different situations. Or at the very least, have multiple viable options.

Plus, as mentioned above, it's not trivial to make this modifier toggleable given the current code infrastructure. I would have to essentially remove the current modifier entirely and replace it with a new one using the accessory interface, which would break all of the current armor that does have the modifier.

But most importantly, making the modifier toggleable is a rather lazy solution to the more core problem that the Glowing modifier is annoying to employ in practical play. The Glowing modifier was made as a direct counterpart to the tool's version. This isn't exactly ideal because while the tool's version has the same drawback, it's much easier to change tools than it is to change armor. Perhaps there's some way to change the Glowing behavior itself so that it's more fitting of its place as an armor piece and less annoying to have but retains the comparison to the tool's version. I'm not sure what that would look like, but I'm open to suggestions on that front.

**Comment by StefanArmand** [comment]
Okay, thank you for your reply. Maybe a way to fix it would be to further decrease the light level required. For example while outside even at night it wouldn't work, but underground while mining it would. That would make it actually useful and not annoying. https://minecraft.gamepedia.com/Light According to the link, at night the brightness is 17% and full darkness its 5%. Maybe make it work at 7-8%?

Or maybe make it rely on world Y level, that would make it easier to program maybe, with it working only underground, and not above the surface.

**Comment by TheIllusiveC4** [comment]
I appreciate the suggestions. The problem that I see with making the Glowing modifier activate in lower light or at certain Y-levels is that this makes it serve the very particular purpose of lighting up underground spaces. This is useful to you, as that's exactly what you want. But this would render it useless to players who actually want to light up places on the surface.

**Comment by StefanArmand** [comment]
I guess you are right, maybe they would want that, but the glowing modifier is still most useful when underground, mining. And if you look at the Tinker's construct modifier it says: "Glowing: if light level at player's location is less than 8, spawn a glowing orb for 1 durability. 1 level." So its made to work underground only, like I was suggesting.

**Comment by TheIllusiveC4** [comment]
> So its made to work underground only

This is untrue as there's nothing in that description to suggest this. Light levels below 8 exist on the surface as well. In addition, simply walk around at night holding a Glowing tool and you'll see that it functions exactly the same as the Glowing armor. This is because the code for both of them are nearly identical. Whether or not this is _intended_ to work only underground is only known to the Tinkers developers themselves, but that's how it works currently. I'm inclined to believe that the Glowing modifier was meant to be used in any situation that requires light, whether that be underground or at night on the surface.

**Comment by StefanArmand** [comment]
I admit I haven't tried the tool version, but if you say that it works the same I believe you. 

Okay, another idea, maybe make it that it lights everything around you, but it doesn't place light sources? Or only temporary ones, I don't know if that is possible.

**Comment by TheIllusiveC4** [comment]
Making it light everything around you like that is technically possible, but it requires some pretty heavy coding and/or some pretty heavy lag due to the way that Minecraft's lighting system works. Even if I could get it working, it would be too much overhead to try and introduce for this single modifier feature.

Placing temporary light sources is also possible, but I don't see the benefits of doing so. It makes it less useful overall because of the temporary nature of the light sources and for the same cost of 1 durability. In addition, it doesn't really address your initial problem that it activates in situations where you don't want it to. It still would, it's just that it would go away after a while, which brings it back to the previous concern again.

**Comment by StefanArmand** [comment]
Actually if its only temporary it would bother me a lot less, because it wouldn't affect mob spawns as much. Also I wouldn't have to worry about trying to find every light source introduced by glowing after building a structure and lighting it myself, they would just disappear on their own. And wouldn't that be a good balancing of it? Right now its pretty OP and makes torches completely unnecessary. If temporary it would feel more balanced, "realistic".

**Comment by TheIllusiveC4** [comment]
I'm not sure I'd agree that it's more realistic to have the glowing bits disappear. That seems like a subjective judgement since it's based on a fantasy mechanic.

Your stance is a bit confusing to me now. Your initial issue seemed to be that the Glowing modifier was too annoying, but now you state that they are pretty OP. These two stances stand on opposite sides of the balancing equation. If it's too annoying to have on all the time, we need to introduce more benefits. If it's pretty OP, we need to introduce more drawbacks. As it stands, isn't the drawback to its OP-ness the fact that it stays activated all the time? Doesn't that serve as a balancing mechanism? Also, you present the idea of a temporary light source as beneficial to you while also positing that it would be a drawback that balances the OP-ness. This seems contradictory.

**Comment by StefanArmand** [comment]
I'm sorry if it seems confusing, I was trying to adapt to what you were saying its possible or not.

"That seems like a subjective judgement since it's based on a fantasy mechanic." Well, yes, that's true, but the way I see it is more like a magical source of light, and usually spells finish their effect after a time. That's why I said its more "realistic", if you compare it with fantasy games in general.

"Your initial issue seemed to be that the Glowing modifier was too annoying, but now you state that they are pretty OP" Sure, my ideal option would have been to turn it on or off, but you say that's not possible so I was starting to think about alternatives, and while doing so I realized its so annoying because it turns on so often and in many places I don't want it to turn on. It is OP because its easy to make an area lit up really fast with the modifier, but annoying because maybe you don't want that area lit up at that time, like when traveling on the surface or building. Putting them on a timer is not an ideal solution but the way I see it is that it would make them somewhat helpful and reduce the annoyance because they eventually disappear in the areas where you didn't want them in the first place.

"As it stands, isn't the drawback to its OP-ness the fact that it stays activated all the time? Doesn't that serve as a balancing mechanism?" Not the way I see it, its just really good when mining, not needing torches and forever having secure mining areas, and really annoying outside with infinite light sources you have to hunt down. With temporary lights ( and I'm not saying its the best option, its just one I thought of now) it would still be useful in mining, with the drawback that if you return you have to relight the area, and outside you still get the drawback that you get the lights, but at least eventually they disappear so you don't have to hunt them down manually.

**Comment by TheIllusiveC4** [comment]
I think you make some compelling arguments, but I'm still not entirely convinced. 

Making the blocks temporary will just flatten the two extremes, so that it's not as useful but also not as annoying. I don't really see the net gain in terms of balance. In addition, we also have to consider that this will be a general nerf for players who just like using Glowing all the time. 

As I've mentioned before, the primary solution for players who only need Glowing in select scenarios is ideally to simply have different armor pieces.

While I did say it's possible, I'm also very adverse to making a temporary block because it introduces some slight overhead and I'd have to make the glowy bit into a whole different block than the Tinkers' Construct one that I'm re-using currently. It would be somewhat unintuitive for people using both.

**Comment by Thunder-Nova** [comment]
May I squeeze something in here, I am thinking something short and simple, minus the command, yet does add a limit.

I do not know if it's possible. So to go with both @StefanArmand ... BUT with @TheIllusiveC4 capabilities.

Just to make things clear I am ok with the current situation of Glowing modifier. But I am the type who likes to give ideas that can be either helpful or at least possible. Glowing is not OP in my opinion.

So I got a few questions:

1. Is it possible to make glowing modifier a stack type single modifier? Exemple: Glowing 1 to 2 similar to Luck. Meaning to upgrade from 1 to 2 doesn't use a modifier.

2. I know light source calculation stops at a certain level of darkness which glowing uses when reaching the peak which @StefanArmand needs to note. So removing commands.
  [ How about sneaking? ]
It's a pretty common method I seen a lot of mods used for some gears I wore in the past. Plus unlike a command, it's not something that can be turn on and off. So no need to become an accessory, and should be easy to update into existing armors by just keeping "glowing" without number as tier 1 and just add 2 to make the next tier. Tier 1 with sneak, Tier 2 no need to sneak.

(I meant crouching, but this reminded me of fallout power armor for some reason)

**Comment by StefanArmand** [comment]
If it would be easier to implement the crouching option seems reasonable.

**Comment by TheIllusiveC4** [comment]
@Thunder-Nova 
I actually had some similar ideas in the wake of this discussion, with the multiple tiers and the sneaking activation. There are still some caveats that I'd have to work out first, but it is a possibility that I will implement those changes.

**Comment by StefanArmand** [comment]
Awesome news, thank you.

**Comment by Thunder-Nova** [comment]
@StefanArmand
Happy to be of help, but just to tip you for later on on suggestions later on; Try to think of ideas, and limits of how vanilla minecraft works.

In this case the biggest problem was light level. There are no mods that expand on vanilla darkness yet, and highly doubt it's gonna be added on an Armor type modpack.

Last thing I want to see is someone quitting due to disputes... Being a minecraft player since before modpacks existed, I seen too much quit due to unreasonable requests. It helps to give more then one idea at least for an end goal. It also helps to avoid personal limits, when there are existing possibilities.

@TheIllusiveC4
Sorry that I for one came into this, yet felt so much possibilities and comprehension of your work. Plus my love for tinker since Hexxit is still strong as ever that seeing a start in armor type, makes me want to help out. Especially in middle ground in disputes,  if I find some logical standpoints.

I have no real knowledge in mod making, yet I do know limits and possibilities. So I try to stick in questions of logical possibilities. I am not the type who likes forcing one's hands.

I do like being asked questions so do feel free to ask me any. I do have a discord account which notifies me better, but it's up to you.

**Comment by StefanArmand** [comment]
I had no intention to "force anyone's hand", and I'm sorry if I created any impression of that. I really love this mod, and this is the only modifier that I felt that maybe needed some tweaks. I tried my best to come up with a reasonable suggestion and if we wouldn't have reached any solution I would have accepted it, of course. But I'm glad that a sensible change was found after all.

**Comment by Thunder-Nova** [comment]
@StefanArmand
No worries, it's pretty common. I have seen a lot of suggestions from other people, but if I can help, for Both sides, I will.
