### ISSUE TITLE
[Suggestion] Change armor cores to look less like vanilla armor

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TheIllusiveC4/ConstructsArmory#142]
I've been quite a few posts like [this one](https://www.reddit.com/r/feedthebeast/comments/ag0j4q/cant_use_this_armor_it_doesnt_go_in_the_armor/) on Reddit. People are often confused by the fact that you can't equip a chestplate core, and I think the main reason is the appearance. It looks like a recolored chestplate.

All of the other Tinkers' tool parts are obviously not complete tool at a glance. Pickaxe heads aren't confused for pickaxes because they lack a handle, for instance. Armor cores need a similar visual indicator.

I recommend renaming them to "armor frames" and cutting a hole out of the center of each texture. Thematically this would make sense, since you patch those holes with armor plates when you make the armor.

**Comment by TheIllusiveC4** [comment]
I've been thinking the same thing for a while also. Personally I'm not sure why people are confused since making armor is just like making any other Tinkers' tool, but I can recognize that the appearance of the armor cores can be misleading. I don't think I want to change the name, at least for 1.12.2, but I'll look into updating the textures at least.

**Comment by TheDeviantCrafter** [comment]
I get the impression that most people who get confused aren't very familiar with Construct's Armory. They just see a chestplate shaped thing. This is the only mod I'm aware of where chestplate shaped items can't be equipped as armor.

I guess it's part of the language of modded Minecraft. Mods have reinforced the idea that armor comes in a specific shape, and people assume items with that shape work as armor.
