### ISSUE TITLE
Compatibility with Cosmetic Armor

### ISSUE THREAD

**Issue by MokahTGS** [TheIllusiveC4/ConstructsArmory#143]
This mod doesn't seem to be compatible with Cosmetic Armor.  I'm wondering if that needs to be specifically added or if there is just some sort of bug.

This is the specific mod I'd like to see have compatibility added:
https://minecraft.curseforge.com/projects/cosmetic-armor-reworked?gameCategorySlug=mc-mods&projectID=237307

**Comment by TheIllusiveC4** [comment]
I just tested it, and it is compatible. I'm able to put Construct's Armory armor in my Cosmetic Armor slots just fine. I don't see why it would be an issue to begin with since it's classified as armor just like anything else that would go in the Cosmetic Armor slots. Even if I could reproduce it, I doubt it's something on my end that's causing the issue.

**Comment by kierajreed** [comment]
There might be a third mod messing it up.

**Comment by CheshireSwift** [comment]
TexFix and/or Mo' Bends were the culprits for me; disabling TexFix and telling Mo' Bends not to apply to player models meant that Cosmetic Armor worked fine with Construct's Armory (possibly unsurprising, given those two don't seem to place nice with Armory in general).
