### ISSUE TITLE
An issue about Frost Walker modifier

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TheIllusiveC4/ConstructsArmory#151]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.3
* Tinkers' Construct: 1.12.2-2.12.0.115
* Mantle: 1.3.3.42
* Forge: 14.23.5.2768

#### Observed Behavior:
When Frost Walker and Autoforge coexist, a player equipped with such boots standing on a Magma Block will make Frost Walker's durability consumption invalid, replaced by Autoforge's durability recovery effect.
#### Expected Behavior:
This shoes is supposed to consume 2 durabilities per fire damage.
#### Steps to Reproduce:

1. I got a pair of Magma Slime Boots;
2. I added Frost Walker modifier by Frosty Soles;
3. /gamemode 0
4. I equipped this shoes;
5. I touched a Cactus block to consume the shoes' durability on purpose;
6. I walked on the Magma Block.

**Comment by TheIllusiveC4** [comment]
Unfortunately, the best solution is to make them incompatible with each other since their abilities are mutually exclusive. In this instance, there's no correct answer as to whether or not the shoes should consume damage because the Autoforge's recovery effect responds directly to the Frost Walker's attempted durability consumption.
