### ISSUE TITLE
armour station gui does not load.

### ISSUE THREAD

**Issue by mommajoe** [TheIllusiveC4/ConstructsArmory#181]
* Construct's Armory: 1.2.4
* Tinkers' Construct: 2.12.0.115
* Mantle: I'm not sure.
* Forge:14.23.5.2811
#### Steps to Reproduce: attempt to load Gui
1.open the armour station gui
2.
3.

[example](https://i.imgur.com/FXaRCva.png)

**Comment by mommajoe** [comment]
sorry for the small amount of information.

**Comment by TheIllusiveC4** [comment]
Can you reproduce this without any other mods?

**Comment by mommajoe** [comment]
I have removed 20 of the mods I used to load, no change. currently have to fob around "in the dark" for lack of a better term if I want to craft armour.

I dread the prospect of heuristically checking each mod to see what the cause is, is there a way I could check for a rendering issue?

**Comment by TheIllusiveC4** [comment]
Are those 20 mods everything you have? You don't necessarily have to find the cause, at least at the moment. Just remove everything except Construct's Armory, Tinkers' Construct, and Mantle and then test to see if this still happens. If it does, then it's likely a problem with Construct's Armory and we can go from there. If it doesn't, then it's likely some other mod and then we can worry about what that could be.

**Comment by mommajoe** [comment]
it appears to be a mod conflict, loaded with bare mods and it worked....

¯\_(ツ)_/¯
 
I guess this is something i'll have to do on my own, thanks for the help!

**Comment by TheIllusiveC4** [comment]
Closing this for now, but if you figure out the cause, you can feel free to reply back and I can re-investigate if it's something I can fix on my end (although that's not usually the case). For figuring it out, you can try and do a binary search by basically taking half of your mods and then testing each half to see where the problem is. Then you take the half that has the problem and keep splitting it by half and testing them until you find the conflicting mod. This way you can try and narrow it down without necessarily testing every single mod.
