### ISSUE TITLE
Need tinker construct?

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/ConstructsArmory#199]
I have tinker construct installed but in the files it's called Tconstruct, but in game it asked Tinker Constructs', any fix for this?

**Comment by TehSeph** [comment]
~~File name **literally** means **nothing** to forge.
What is the actual error you're getting?~~

edit: Just realized this is the ConArm github, not the TCon github. Does this issue even belong here?

**Comment by kierajreed** [comment]
Please be more specific. Error logs, file structure, and error screenshots would help a ton.

**Comment by TheIllusiveC4** [comment]
What SkyHawkB said. I'm not even sure of the exact nature of your problem. Either way, this isn't really an issue that's appropriate for the Construct's Armory repository since it's only related to Tinkers' Construct so I'm going to go ahead and close this. 

You're still free to explain your issue in more detail here and I'll try to help you out, but it might be more appropriate to seek help on more general forums or maybe hop into [my Discord server](https://discord.gg/JWgrdwt) instead.
