### ISSUE TITLE
Armors do not gain XP under Tinker Tool Leveling

### ISSUE THREAD

**Issue by zauberparacelsus** [TheIllusiveC4/ConstructsArmory#200]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-1.2.5.3
* Tinkers' Construct: 1.12.2-2.13.0.171
* Mantle: 1.12-1.3.3.55
* Forge: 14.23.5.2847
* Tinker's Tool Leveling: 1.12.2-1.1.0
#### Observed Behavior:
When used alongside Tinker's Tool Leveling, armors do not receive XP
#### Expected Behavior:
Armors should receive XP
#### Steps to Reproduce:
1. Run around and get hit by enemies?

**Comment by Jennifercutixx** [comment]
I don't know why you're not gaining xp from being hit by mobs. Because when i use the armor i gain xp from getting hit by mobs with Tinker's Tool Leveling.

**Comment by zauberparacelsus** [comment]
I'm not sure either.  However, a few days after reporting this issue, the problem went away on its own.  I think it may be either because I unknowingly [A] uninstalled the offending mod or [B] updated the offending mod to a version that fixed whatever caused the conflict.

**Comment by Jennifercutixx** [comment]
that sounds more like what happend to me. like i mod alot of games and versions of the mod can mess with a mod which supports it. Because i had issues where mods didnt work with others and causes can be the version of it. But its good that you have sorted it out. Like tbh to me i dont think its a bug with the mod. just an update mod problem.

**Comment by TheIllusiveC4** [comment]
Well if this issue solved itself then I'll just close this for now.
