### ISSUE TITLE
Skeletal and Indomitable toughness bonuses not affected by toughness modifiers

### ISSUE THREAD

**Issue by Xanthiosaurus** [TheIllusiveC4/ConstructsArmory#212]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12-1.2.5.3
* Tinkers' Construct: 1.12-2.13.0.179
* Mantle: 1.12-1.3.3.55
* Forge: 8.0.99.99
#### Observed Behavior: 
The skeletal trait only increases toughness by 0.5x the base toughness, even if the armor has other toughness modifiers (such as polished, diamond, or Indomitable)
#### Expected Behavior: 
The skeletal trait would increase overall toughness by 1.5x
#### Steps to Reproduce:
1. Create a piece of armor with the skeletal modifier (e.g. flint plates and skeletal trim; total toughness of 1.5
2. Polish armor (like sponge; toughness 5)
3. Total armor toughness of 5.5

Same thing happens with steel, but 1.2x instead of 1.5x.

If you have steel trim and bone plates, total toughness is 1+0.5+0.2=1.7. If you polish it with sponge, it goes up to 5.7, and if you add diamond, it goes up to 7.7.

Not sure how much of this is intentional for balance, but it took me a while to figure out why my toughness wasn't going up by much after polishing my armor.

**Comment by SonicX8000** [comment]
I always thought that this was intended since it boosts the Toughness from the Plate Material. Polishing & Diamond Modifier would be treated as 'Bonus Toughness' which Indomitable & Skeletal doesn't affect as it only checks the Toughness Value from the Plates.

In this example I'm using Sponge Plates, which gives 5 Toughness.

Sponge Plates: 5 Toughness
Indomitable is +20% Toughness so +1 "5 x 1.2 = 6"
Skeletal is +50% Toughness so +2.5 "5 x 1.5 = 7.5"
Diamond is a flat +2 Toughness.

Total: 5.5 Bonus Toughness

All that together will give me 10.5 overall Toughness. If I were to use a Polish for higher toughness that's only going to be treated as bonus toughness. In Metallurgy there's a material called "Krik" which has a Toughness Value of 9 for it's Plates so let's use that as a Polish...

Current Base Toughness is 5, Krik is 9 Base Toughness so Polishing will only grant +4 Bonus Toughness. My Toughness is now at 14.5.

Now... if you replace the plates with Krik instead of Polishing...

Krik Plates: 9 Toughness
Indomitable is +20% Toughness so +1.8 "9 x 1.2 = 10.8"
Skeletal is +50% Toughness so +4.5 "9 x 1.5 = 13.5"
Diamond is a flat +2 Toughness.

That's 8.3 Bonus Toughness, mixed with the modifiers & traits... will bring it to 17.3 Toughness.

**Comment by TheIllusiveC4** [comment]
Z-Tunic has it right, this behavior is intended. The toughness boosts calculates from the base amount, not the total amount.
