### ISSUE TITLE
[Enhancement] Replacing armor parts

### ISSUE THREAD

**Issue by YaibaToKen** [TheIllusiveC4/ConstructsArmory#22]
I would like to suggest the ability to repplace parts of an armor piece, same as you can do with tools.

**Comment by TheIllusiveC4** [comment]
This has actually already been implemented in my dev build, so it'll definitely be in the next public update.

**Comment by YaibaToKen** [comment]
Congrats on the mod btw. a quick question, off topic, are the toughness levels supposed to be so weird? A wooden kit will currently give an armor piece one of the highest toughness levels available (3, there are only 2 or 3 kits that go higher).

**Comment by TheIllusiveC4** [comment]
I calculated the toughness based on the stats from the Tinkers' tools. In the context of the actual armor, wood having high toughness isn't so bad since its other stats are so low. But I can see what you mean that such a cheap kit could bring another armor piece to a high toughness. I'll probably bring this down in the future. It's just a weird result of trying to make a counterpart to the tools' sharpening kit. Now that I think about it, maybe I'll just remove the toughness increasing aspect of it, or change something else about it.
