### ISSUE TITLE
Toughness of armor has no effect

### ISSUE THREAD

**Issue by slammaja** [TheIllusiveC4/ConstructsArmory#23]
Hi,

all armor pieces that are supposed to increase toughness don't do so. First I noticed because one mod of mz modpack adds GUI element showing total toughness, and after some testing - comparison with armor with same toughness level and taking damage - it seems it really doesn't work. 
I have conarm-1.12.2-0.0.8-a and TConstruct-1.12.2-2.9.1.65 installed Forge client/server 14.23.2.2611.
BTW crafted armor pieces have rarities from levels-2.0 mod and qualities from QualityTools-1.0.6.

This issue aside, your mod is great! I've been waiting for something like this since Tinker's Defense for MC1.7.10!

**Comment by kierajreed** [comment]
Since you are playing a modpack, this could be a mod compatibility issue. Can you replicate this bug using only TiCon and the latest ConArm?

**Comment by TheIllusiveC4** [comment]
I can confirm that toughness does indeed work. How toughness is implemented in this mod would not be caught by whatever mod you have that shows toughness in the GUI. This alternate approach was necessary in order to get the armor to function properly with the traits that it has.

That said, testing this caused me to find out that the armor "calculate damage" code is a total mess and needs to be rewritten so I'll be able to look into this further if needed.
