### ISSUE TITLE
Crash on opening of armor forge gui

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [TheIllusiveC4/ConstructsArmory#236]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
* Eclipse IDE: java-2019-06
#### Observed Behavior:
Game crashes when right clicking armor forge
#### Expected Behavior:
Armor forge gui opens
#### Steps to Reproduce:
1. Download, extract, run `gradlew setupdecompworkspace` and then `gradlew eclipse` and import project into eclipse workspace
2. Errors at [client/gui/GuiPreviewPanel.java line 54](https://github.com/TheIllusiveC4/ConstructsArmory/blob/a6c52ed614c540a250785434337712b73f01db74/src/main/java/c4/conarm/client/gui/GuiPreviewPanel.java#L54) and at [client/gui/GuiArmorStation.java line 565](https://github.com/TheIllusiveC4/ConstructsArmory/blob/a6c52ed614c540a250785434337712b73f01db74/src/main/java/c4/conarm/client/gui/GuiArmorStation.java#L565) listed as `Cannot directly invoke the abstract method drawGuiContainerBackgroundLayer(float, int, int) for the type GuiContainer`
3. Ignore as the mod works as normal in actual play
4. Run project
5. Grab an armor forge and place it in world and right click it
6. Game crashes
...

[Crash Report](https://hastebin.com/odecaxavid.rb)
[latest.log](https://hastebin.com/anikulazin.md)
[debug.log](https://github.com/TheIllusiveC4/ConstructsArmory/files/4828339/debug.log)

**Comment by TheIllusiveC4** [comment]
> Ignore as the mod works as normal in actual play

You shouldn't ignore them since the compilation errors are the direct cause of the crash.

This isn't an issue with the mod, it's an issue with your project setup. The lines you're referencing are supposed to point to `GuiInfoPanel` from Tinkers' Construct, but instead are pointing directly to `GuiContainer` from vanilla, which is abstract and thus cannot be invoked directly. You can try to go directly to which method `super` is calling to verify. I'm not sure why this is the case, but something is definitely off here.

Before making any future issues on this tracker during your development process, please verify first that the problem is also present in the official production version of the mod.
