### ISSUE TITLE
Crash when using Tweakers Construct and Metallurgy 4

### ISSUE THREAD

**Issue by Mock17** [TheIllusiveC4/ConstructsArmory#241]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2854
* Metallurgy 4: Reforged: 1.0.2
* Tweakers Construct: 1.5.4

#### Observed Behavior:
Posting the issue here because the game says this is the mod that's causing conflict, apologies if it isn't the case.

I was trying to balance some of the stats of the armors using tweakers construct, everything was working fine until I tweaked the materials added by the Metallurgy mod. when I try to open the game it crashes saying that there was a loading problem with this mod. 

#### Expected Behavior:
The stats should change accordingly to the values I put on the Tweakers Construct config file. 

#### Steps to Reproduce:
1. Install the mods listed
2. Tweak the stats from the materials added by metallurgy 
3. Open the game and it will crash 

Crash Log: https://pastebin.com/j6A2hk6y

Again im sorry if this isn't a ConArm problem, but rather something with the other mods, im posting here because of what the game says.

**Comment by TheIllusiveC4** [comment]
No worries, sometimes it's hard for even modders to discern the problem.

Anyway, it's a little hard for me to tell exactly because I'm not familiar with Tweaker's Construct. However, on line 16 of the crash report, you can see that it passes through a Tweaker's Construct method after Construct's Armory. So I don't think this is a Construct's Armory problem. From what I can tell, it seems like the crash is due to something being "1,0" when it should be a number instead like "10". Double check all of your files again for something like that.

**Comment by Mock17** [comment]
Oh I think I found the problem, it was difficult to see due to the comma being buried in lines and lines of symbols, thank you so much! i'll be looking into the crash logs from now on.
