### ISSUE TITLE
Error Notice

### ISSUE THREAD

**Issue by Override5** [TheIllusiveC4/ConstructsArmory#242]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.4
* Tinkers' Construct: 1.12.2-2.13.0.183
* Mantle: 1.3.3.55
* Forge: 8.0.99.99
#### Steps to Reproduce:
1. Make any armor, using things with more then one trait help
2. Level up the armor until you get the error message in the Armor Forge
3. Make sure you have Modifiers avaiable (See attachment, ATT.2)

[Error message.docx](https://github.com/TheIllusiveC4/ConstructsArmory/files/5102599/Error.message.docx)

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue, the additional modifiers from leveling work fine for me. Is this without any other mods installed? Because that GUI error is non-standard, it's not listed in the lang files of either Construct's Armory or Tinkers' Construct. For insufficient number of modifiers, it should say `Not enough Modifiers (x needed)`. I'd assume this issue, if valid, is caused by another mod tweaking this behavior.
