### ISSUE TITLE
Constructs armory - lucraftCore compatibility issue

### ISSUE THREAD

**Issue by sheepAlive** [TheIllusiveC4/ConstructsArmory#246]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Steps to Reproduce:
1. Install conarm and its dependencies  
2. Install lucraftCore
3. Right click conarm Armory Station or Armory Forge 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Jennifercutixx** [comment]
this would be a mod conflict since tinkers armory doesnt have an issue within its self. but for your problem. game crashes can be for alot of reasons.
I am gonna guess and say that those are the only mods are installed. so the first cause of crash can be a script conflict with the gui's of the mods. I would reconmend putting a conflict on the lucraftcore page to. since this looks like a gui conflict.

**Comment by sheepAlive** [comment]
I will do that, thanks for the response

**Comment by Jennifercutixx** [comment]
Your welcome, i'm drunk but ill help as much as i can. and ye i have found out if u use texfix it will cause that issue

**Comment by Jennifercutixx** [comment]
since i have over 160 mods and no copnflict with mo bends and twilight forest and mods like that. i think its bc tex fix causes vinilla textures to override armory so it makes them invisable. but im drunk so be hard for me 2 say rn.

**Comment by TheIllusiveC4** [comment]
This is a known issue, but I don't specifically know the cause. It has something to do with how Lucraft interacts with the player model, which doesn't play nice with the player model rendered in the Armor Forge's preview panel. Until given more information otherwise, I'll conclude that this is on Lucraft's side to fix properly and the current workaround is to set the `Compact GUI` option in the Construct's Armory configuration to `true` which will disable the preview panel entirely.
