### ISSUE TITLE
New set of armor

### ISSUE THREAD

**Issue by Matheuws58** [TheIllusiveC4/ConstructsArmory#27]
You could create a new type of armour that is more though than the normal one, using a lot more materials and making the player slower, making it no so op as it looks like just making more variety of armor that can be done just like the difference between the broadsword and the cleaver.
But this is just a suggestion and I am not mod understander (and not adept in English).
I think is a good idea and could make the mod more immersive and fun to play with.

**Comment by TheIllusiveC4** [comment]
Sorry, but this is not a feature that I'll be adding to the mod. The problem comes in two parts:

1) The strongest armor currently available reduces damage by 80%, which can be increased to ~92-96% with protection modifiers. That's a lot of damage reduced already. Stronger armor makes combat trivial, and I don't want to do that much further than what vanilla already provides to avoid power creep.

2) Movement speed debuffs are not a fun mechanic to me. The difference between the broadsword and cleaver is not analogous because attack speed does not actively impede the player, and the payoff is sufficient. A penalty to movement speed affects everything that you do, and the only benefit is an extremely small damage reduction bonus. Maybe this is just me, but I would never pick the slower armor just for a small boost in defense. Even in combat situations, the increase in defense may not even justify the loss in maneuverability.

**Comment by Matheuws58** [comment]
There are some good arguments, but I will try to find some truly good ideas to help the development of the mod, because what is the point of waiting the mod be done without helping a little bit if I liked the project?

**Comment by TheIllusiveC4** [comment]
I appreciate your willingness to help. I will listen to any and all suggestions that you may have.
