### ISSUE TITLE
Incompatibility of tinkers construct with other attachables geometry manipulating mods

### ISSUE THREAD

**Issue by SYUMJOBA** [TheIllusiveC4/ConstructsArmory#276]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.10
* Tinkers' Construct: 1.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2855
#### Steps to Reproduce:
1. Download Tconstruct with conarm, forge and Mantle (it is not version sensitive as far as I found it)
2. also put in your mods the Vic's modern warfare mod or the Mo'bends (I have not tested it, but I believe that also the Hero's mod could cause problems)
3. run the game and equip some conarm armor, you'll see weird stuff going on. 
...

NOTE: The only mod that breaks is Tinker's construct armory (conarm), while mw armor remains 100% accurate, you can equip it with no problems, the UV and geometry works as expected, it looks like only Tconstruct is the problem
I don't expect this to get fixed, since I believe that the problems lays deeper into the Tconstruct dependencies, but if you'r mind fixing, I'd love to craft my own custom armor while shooting with a colt to enemies.
Also, the problem are only the UV's and geometry, it is a graphical thing, the game logic remains flawless.

And please, I know this is a compatibility issue, so I was not sure if labelling this as bug or feature request. I'd be glad to be corrected. Thanks.

Cheers!

This is how it behaves:
![Screenshot (629)](https://user-images.githubusercontent.com/61433707/145799500-0093a497-5542-47a0-a31d-26f383e8602d.png)
![Screenshot (630)](https://user-images.githubusercontent.com/61433707/145799671-248ce205-a504-4b53-8bb3-e176f66acd64.png)

**Comment by TheIllusiveC4** [comment]
This issue has been reported already. It is not something that only affects Construct's Armory armor, it affects many other modded armor that uses their own models such as Botania. It is on the Vic's or Mo'Bends developers to address since they are the ones manipulating the player models in the first place, and nothing that is done in Construct's Armory is special other than providing a custom armor model so there's not much I can do to address this on my end anyways.
