### ISSUE TITLE
Game crash when hit by Guardian beam while wearing armor piece with Rough attribute

### ISSUE THREAD

**Issue by IndigoAvemour** [TheIllusiveC4/ConstructsArmory#43]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.12.2-0.0.17-b
* Tinkers' Construct: 1.12.2-2.10.0.81
* Mantle: 1.12-1.3.2.24
* Forge: forge-14.23.3.2702

#### Observed Behavior:
Game crashed when hit by a Guardian's beam while wearing a Constructs Armory helmet that has the Rough attribute. Happened twice. Game didn't crash when attacked by vanilla Zombie, Mobulition's Knight Zombie, or Creeper's explosion. In all non-Guardian cases I haven't seen the Rough effect happen.

#### Expected Behavior:
Whatever I assume the Rough attribute is supposed to do, which I imagine to be the equivalent to vanilla enchantment Thorns.

#### Steps to Reproduce:
1. Wear a CA armor piece with Rough attribute
2. Find Guardian in survival mode
3. Get attacked with beam

Crash Log: 

[First crash](https://pastebin.com/G88LH7Zp)
[Second crash](https://pastebin.com/VUETuCsV)

**Comment by TheIllusiveC4** [comment]
Okay, so this is due to the Guardians' Thorns characteristic triggering a recursion that I hadn't considered. I'll try and push out a hotfix as soon as I can. 

As for the Rough trait in general, I tried it out and it does indeed work. Note that the Rough trait is based on durability, so it will do almost no damage if your armor is at full durability. All the same, you should still be able to see the attackers get harmed when they attack you.
