### ISSUE TITLE
Tool tip for text overlap in Materials and You Armory Addendum

### ISSUE THREAD

**Issue by VallenFrostweaver** [TheIllusiveC4/ConstructsArmory#45]
#### Versions:
Construct's Armory: 1.12.2-0.0.19-b
Tinkers' Construct: 1.12.2-2.10.0.81
Mantle: 1.3.2.24
Forge: 14.23.3.2655
#### Observed Behavior:
Hover over a material trait and the tool tip goes under the book typeface making it hard to read
#### Expected Behavior:
Tool tip overlaps the book and text
#### Steps to Reproduce:
1. Open Materials and You Armory Addendum
2. Go to page with material Traits listed (like Flint has Mundane II on the core) and hover pointer over traits or word descriptions to populate a tool tip
3. Any of the text Tool tips that pop up are under other typeface from the page instead of the entire tooltip window being on top.

**Comment by TheIllusiveC4** [comment]
This is actually an issue with Mantle, which provides the library code for the book data. You can see this behavior in the base Materials and You book from Tinkers' Construct as well. It's just made slightly worse in the case of this mod because of how the text is positioned (out of necessity, since the information isn't the same length as base Tinkers'). I'll see if I can figure out a workaround or at least mitigate the issue, but worst case scenario is that this is just how it is until Mantle addresses it.

**Comment by TehSeph** [comment]
This happens in Tinkers itself, too.
https://github.com/SlimeKnights/TinkersConstruct/issues/2115

**Comment by TheIllusiveC4** [comment]
This is actually an issue with Mantle and how it renders the book tooltips. You can see this behavior in the original Materials and You book as well, it's just exacerbated in this mod due to the way the text is positioned. I just tried a couple ways to try and get around this, but it all looked a little off. I'll keep playing around with this, but worst case scenario is that this is just how it is until Mantle addresses it.

**Comment by VallenFrostweaver** [comment]
Ah! Never noticed. Thanx!
