### ISSUE TITLE
(Config Suggestion) Adjustable Armor, Toughness and Durability Values.

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/ConstructsArmory#52]
I am currently making a modpack and want to use your Mod together with TiC as the main mods for Tools and Armor.

So I removed all normal minecraft or other moded armor so players can only make your cool Tinker style armor.

But I have one problem.
Your armor gets shredded by the monsters as I have damage for monsters scaling up over time to a certain point.

This results in your armor being useless in mid to end game times even fully upgraded Manyullyn/Steel Armor will only reach an armor value that is like 2 of the armor indicators greater than Diamond.

If the values where adjustable in the configs or a separate config file that grabs materials or something (like the yoyos mod does) so modpack makers could use your armor better it would be really nice.
Since there are no modifiers to increase toughness or armor points!

And as resistance works in a different way than armor the modifier doesn’t help much even if it scales to resistance 8 which is kind of high for resistance and I think 5 would have been sufficient.

But with the way damage is calculated in minecraft your armor can’t competed with others once damage was modified which I find sad since your mod is something I have been waiting for since the first time I played with TiC back in MC 1.7.10.

PS: don’t get me wrong I still flipping love this mod, heck when I first saw it I was like that’s it that’s the thing I was missing for this pack.

**Comment by kierajreed** [comment]
I think that rather than bloating the config, it would be better to add CraftTweaker compatibility to this mod, so pack makers can change the values in a script.

**Comment by TheIllusiveC4** [comment]
CraftTweaker support has already been integrated for some time: https://github.com/TheIllusiveC4/ConstructsArmory/wiki/CraftTweaker-Integration

You can tweak any of the material stats as you deem necessary for your pack. If you have any questions about its usage, feel free to ask me.

With that said, I'd just like to note that I'm not trying to compete with other modded armors. I think too many trivialize damage as is. I'm focused on versatility rather than raw damage protection, and I try to design around the confines of what vanilla offers you in terms of protection values. But of course I understand this is not universally applicable to all pack designs, which is why I introduced CraftTweaker support for your exact dilemma.
