### ISSUE TITLE
Indomitable Toughness overwritten

### ISSUE THREAD

**Issue by LetterShapedGlyphs** [TheIllusiveC4/ConstructsArmory#77]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory:  1.0.0
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.12-1.3.2.24
* Forge: 14.23.4.2707

#### Observed Behavior:
Polishing armor with steel "Indomitable" trait can decrease toughness.
#### Expected Behavior:
Polishing armor raises toughness, or does nothing.
#### Steps to Reproduce:
1. Make any piece of armor with steel plates.
2. Observe toughness rating of 5.4
3. Polish with weaker material.
4. Armor now has decreased Toughness.

Going through the code, this is because Tinker's Construct applies all trait effects before modifier effects. As this is not something that can easily be fixed in this mod, a warning either under the polishing kit or the Indomitable modifier would be appreciated.

**Comment by TheIllusiveC4** [comment]
I think I can fix this actually, I'll try my hand at it as soon as I can.

**Comment by terrapin47** [comment]
Ha, I was just about to submit this issue.  I can add to this however, it has nothing to do with indomitable.  This will occur on any armor piece that you polish, if the polish is weaker it will actually decrease the toughness.

Also, you would expect the modifiers to be re-calculated upon polishing, so that polishing only effects the base toughness, which is then increased by other modifiers.

For example, if you apply a diamond as a modifier, and then polish an armor afterwards, the diamond's effect will be overwritten.
