### ISSUE TITLE
Suggestion + bug

### ISSUE THREAD

**Issue by Moobien** [TheIllusiveC4/ConstructsArmory#8]
Being able to attach jetpacks from the various mods that add them would be cool.

The bug I found is as follows.  I made a nice armor but the scale is that of a baby zombie so in third person view it looks like i have a baby armor growing out of my body

**Comment by TheIllusiveC4** [comment]
I'll look into that jetpack thing. No promises though.

Now, about that bug. That's interesting. I have no idea what could be causing that, especially since I haven't ever encountered it myself. Would it be possible to include a couple screenshots of what it looks like? I might be able to figure it out from an image.

And does this happen with just Construct's Armory and Tinker's Construct installed? I just want to see if it could perhaps be due to some kind of interaction with another mod.

**Comment by Moobien** [comment]
https://imgur.com/a/r7BKe

**Comment by Moobien** [comment]
ok so I TRIED testing it in my minimal mods install.  

conarm-0.0.2-a
Mantle-1.12-1.3.1.21
TConstruct-1.12-2.7.4.34

I get CTD on every startup. 

https://gist.github.com/Moobien/4be67e7b4067dfa3eee3295c545729ed
https://gist.github.com/Moobien/8a4034305951f503c855680c3c6b3b75

Interestingly my install for the modpack I am building loads up fine.

**Comment by Moobien** [comment]
Updated to conarm-1.12.2-0.0.4-a and still getting crashes in test install.

Here is the log for my modded install.

https://gist.github.com/Moobien/db0666d47476959df4f11a8bdd47027e

**Comment by TheIllusiveC4** [comment]
For the crashes, you have to update to a newer version of TConstruct. It was my own oversight that I didn't embed this dependency in, I'll fix that in the next update. But just update TConstruct and that should stop.

**Comment by TheIllusiveC4** [comment]
I honestly have no idea what's going on with that rendering issue. I can't replicate it, I made some armor and it all looks fine on my install with just ConArm, TCon, and Mantle. I can only assume it's due to some other mod interfering with the rendering code. Do you have Optifine installed? That's usually the culprit for rendering issues like this, but it's just a guess.

The only thing I can do at this point is, if you give me your modlist, I could try and figure out which mod is causing this issue and dive in from there.

**Comment by Moobien** [comment]
https://gist.github.com/Moobien/99d0f5bdf12efde354e165e1bb78ac27

**Comment by Moobien** [comment]
Updated tinkers for my test install and then tested both with and without optifine snd in both cases the armour looked perfect. On a side note i found you another bug. When you put 4 bits of armour onto an armour stand the chest feet and legs go on fine but the helmet goes on rotated 90 degrees to the right

**Comment by TheIllusiveC4** [comment]
Okay, I'll dig through your modlist sometime and see if I can identify what's going on then.

I actually totally forgot to do any testing on armor stands. Thanks for letting me know, I'll try and get that fixed also.

**Comment by Moobien** [comment]
Sorry to be giving you more work to do

**Comment by Moobien** [comment]
I know one of the mods in my list is stopping fence gates from being activated by pressure plates lol

**Comment by TheIllusiveC4** [comment]
I'm slowly going through your modlist, but it's quite extensive so it'll take some time.

If you're so inclined, you could help me on your end by trimming down the potential mods that could be causing this issue. Start out with Construct's Armory, Tinkers' Construct, and Mantle, and then add in half of the mods on your list and see if the armor is still rendering tiny. If not, then get rid of all of those and do it again with the other half. Keep trimming it down by half until you reach the point where you only have a handful of mods that could be causing the issue.

**Comment by Moobien** [comment]
I found the offending mod. Once galacticraft was removed the armour turned full size

**Comment by TheIllusiveC4** [comment]
Oh, nice! Thanks for letting me know. I'll try and figure out what's going on with Galacticraft and see if I can fix it on my end.

**Comment by Moobien** [comment]
any luck on finding why GC doesn't like your armor?

**Comment by TheIllusiveC4** [comment]
I haven't looked too closely yet, but I think Galacticraft doesn't like armor that extends ModelBiped. The solution I came across is that I might have to implement support for Render Player API.

**Comment by Moobien** [comment]
I noticed when I ran the analysis with the LagGoggles mod that the player seems to be classed as a GC entity.

The player is listed as micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP

**Comment by TheIllusiveC4** [comment]
Before I started anything, I wanted to try and duplicate your bug. Oddly enough, installing Galacticraft and Construct's Armory did not change anything about the rendering size of the armor. Since I cannot replicate this issue, my hands are tied once again. Did you make sure that both mods are updated to the latest versions? You could try it yourself, install Galacticraft and Construct's Armory in a clean instance and see if the problem still occurs.

**Comment by Moobien** [comment]
I updated Conarm, GC and a couple of other mods as well as added a few more for my modpack testing and oddly enough the armors look full size now. 

I assume you havent implemented part swapping yet? Eg adding new plates to the armor etc

**Comment by TheIllusiveC4** [comment]
Nope, no part swapping yet. That's on the to-do list.
