### ISSUE TITLE
Request: Toggle Keys for certain modifiers

### ISSUE THREAD

**Issue by terrapin47** [TheIllusiveC4/ConstructsArmory#88]
I put a frosty modifier on my boots, but I ended up just making another pair of boots because I'd constantly mess up my friend's farm every time I walked by it.  Having a toggle key for that modifier would be great.

Maybe for others too, such as speedy and jump?

**Comment by TheIllusiveC4** [comment]
No toggle keys for modifiers. Accessories were made specifically for toggling, and those have very strict requirements to be made. Tinkers' does not have a toggle mechanic for their modifiers, so neither will this mod. Specifically for Frosty, the vanilla Frost Walker enchantment can not be toggled either. Having a set of armor that works universally for your needs because you can turn specific modifiers on and off defeats the purpose of tinkering with multiple sets depending on the situation.
