### ISSUE TITLE
[Suggestion] Add a modifier that works like Goggles of Revealing

### ISSUE THREAD

**Issue by aaronhowser1** [TheIllusiveC4/ConstructsArmory#92]
It would be great if we could have Goggles of Revealing without having to give up a CA helmet I think.

**Comment by TheIllusiveC4** [comment]
From the FAQ:
> Q. Can you add a modifier/material to support ____?
A. No. I could, but I won't. As soon as I add support for one mod, then I won't have any reason not to add support for any and all mods. Considering the scope of possibilities, this is a huge endeavor and will only end up bloating this mod with a bunch of optional features. In addition, I'd rather have the other mods add support on their end because then they have full control over what kind of integration to introduce, if any.

**Comment by Entoarox** [comment]
@aaronhowser1 Just in case you are completely unaware, you can put the goggles into the `head` bauble slot, not only allowing you to wear any helmet with it, but also letting you have more vis discount since you can wear a discount-providing headpiece with the goggles.

**Comment by aaronhowser1** [comment]
@Entoarox I actually had no idea, thanks!
