### ISSUE TITLE
Request: Apiarist's armor

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TheIllusiveC4/ConstructsArmory#95]
Forestry adds Apiarist's armor that protects you from bee stings. I'd like to be able to create Construct's Armory armor with the same trait.

**Comment by TheIllusiveC4** [comment]
From the FAQ:

> Q. Can you add a modifier/material to support ____?
A. No. I could, but I won't. As soon as I add support for one mod, then I won't have any reason not to add support for any and all mods. Considering the scope of possibilities, this is a huge endeavor and will only end up bloating this mod with a bunch of optional features. In addition, I'd rather have the other mods add support on their end because then they have full control over what kind of integration to introduce, if any.
