### ISSUE TITLE
[Suggestion] No camera speed effect on armor speed modifiers

### ISSUE THREAD

**Issue by Mike-U5** [TheIllusiveC4/ConstructsArmory#98]
The more speed you have on your armor, the more unbearable your FOV becomes.
A full Cobalt set with speed makes the game unplayable. If at all possible, please remove the FOV changes that come with the speed bonuses from armor, or make it a config option.

**Comment by TheIllusiveC4** [comment]
Sure, I'll make this a config option or something.

**Comment by kierajreed** [comment]
I think there's a mod to do this (remove FOV changes from Speed/Slowness).

**Comment by TehSeph** [comment]
@Mike-U5 @SkyHawkB [NoFov](https://minecraft.curseforge.com/projects/nofov). I've been using is since the day it was released. Truly a blessing to those of us with motion sickness. Same thing goes for [NoNausea](https://minecraft.curseforge.com/projects/nonausea).

**Comment by kierajreed** [comment]
I really like NoNausea's config too! Also I like the Speed FOV change\*, but to each their own.

\* At low levels. At high levels it's crazy.

**Comment by TheIllusiveC4** [comment]
@SkyHawkB 
I could consider making this proposed FoV config option more robust, such as making it a configurable percentage or capped value.

**Comment by Mike-U5** [comment]
@TheIllusiveC4 Thanks for the response. :)

@TehSeph That disables **all** FOV changes. I just want the ones on the speed effect gone since that gets a bit overzealous.

**Comment by TheIllusiveC4** [comment]
@Mike-U5 and others who may be interested,
I've removed this config option in the latest update and split this functionality into a separate mod, [Custom FoV](https://minecraft.curseforge.com/projects/custom-fov). This is because I wanted to introduce more robust FoV configuration options without bloating this mod with something that is a largely unrelated QoL feature. The new mod is much more powerful in this regard, so please use it in the future if you're looking for FoV options.
