### ISSUE TITLE
Armor not working with non-player entities

### ISSUE THREAD

**Issue by RedstoneParadox** [TheIllusiveC4/ConstructsArmory#99]
#### Versions:
* Construct's Armory: 1.12.2-1.0.2
* Tinkers' Construct: 1.12.2-2.10.1.87
* Mantle: 1.12-1.3.2.24
* Forge: 14.23.4.2756

#### Observed Behavior:

Armor doesn't work properly on non-player entities.

#### Expected Behavior:

The opposite.

#### Steps to Reproduce:
1. Give a Zombie or skeleton some armor
2. Attack it to show that traits like rough do not work
3. Additionally, giving it to a zombie shows that the shoulders and gloves are rendered incorrectly: 
![minecraft 1 12 2 8_16_2018 7_13_00 pm](https://user-images.githubusercontent.com/26368796/44244529-3cf3c400-a189-11e8-8fb9-76eaa16afcd8.png)

**Comment by TheIllusiveC4** [comment]
The armor is not supposed to work on non-player entities. This is not really by design per say. Very early on in development, I remember changing all of the conditions from EntityLivingBase to EntityPlayer. I really wish I could remember why I did that so I can review whether or not it's actually necessary. As for a resolution, I'll try and see if I can figure something out.

In addition, I'll look into the shoulders and glove rendering bit. That probably shouldn't be happening.
